app:
    resource: '@AppBundle/Controller/'
    type: annotation

frontpage:
    path: /
    defaults: { _controller: AppBundle:Default:frontpage }

login:
    path: /game/login
    defaults: { _controller: AppBundle:Security:login }
logout:
    path: /logout

game_landing:
    path: /game
    defaults: { _controller: AppBundle:Game:landing }
game_new:
    path: /game/new
    defaults: { _controller: AppBundle:Game:newGame }
game_play:
    path: /game/play
    defaults: { _controller: AppBundle:Game:play }
game_end:
    path: /game/end
    defaults: { _controller: AppBundle:Game:endGame }
game_next_question:
    path: /game/nextquestion
    defaults: { _controller: AppBundle:Game:nextQuestion }
game_check_answer:
    path: /game/checkanswer
    defaults: { _controller: AppBundle:Game:checkAnswer }


user_index:
    path: /game/users
    defaults: { _controller: AppBundle:User:index }
user_show:
    path: /game/user/{id}
    defaults: { _controller: AppBundle:User:show }
    requirements:
        id: \d+
user_register:
    path: /game/user/register
    defaults: { _controller: AppBundle:User:register }
    methods: [GET, POST]
user_update:
    path: /game/user/update/{id}
    defaults: { _controller: AppBundle:User:update }
    methods: [GET, POST]

word_import:
    path: /game/importwords
    defaults: { _controller: AppBundle:Word:import }