AppBundle\Entity\Student:
    type: entity
    table: 'student'
    id:
        id:
            type: bigint
            generator: { strategy: AUTO }

    fields:
        experimental:
            type: boolean
            options:
                default: 0
        currentLevel:
            type: integer
            options:
                default: 0
        highestLevel:
            type: integer
            options:
                default: 0
        timePlayed:
            type: integer
            options:
                default: 0
        errors:
            type: integer
            options:
                default: 0

    oneToMany:
        games:
            targetEntity: Game
            mappedBy: student
        attemptedWords:
            targetEntity: AttemptedWord
            mappedBy: student