AppBundle\Entity\User:
    type: entity
    table: 'user'
    id:
        id:
            type: bigint
            generator: { strategy: AUTO }

    fields:
        username:
            type: string
            length: 25
            unique: true
        password:
            type: string
            length: 64
        email:
            type: string
            length: 64
            unique: true
        isActive:
            column: is_active
            type: boolean

    oneToOne:
        userProfile:
            targetEntity: UserProfile
            cascade: ["persist"]
            joinColumn:
                name: user_profile
                referencedColumnName: id
        student:
            targetEntity: Student
            inversedBy: user
            cascade: ["persist"]
            joinColumn:
                name: student_id
                referencedColumnName: id